In [1]:
import numpy as np
np.version.full_version

'1.19.2'

In [2]:

list_example = [0, 1, 2, 3, 4, 5]
type(list_example)

list

In [3]:
print(np.array(list_example))

[0 1 2 3 4 5]


In [4]:
matrix_example = [[0,5,10,15],[20,20,40,50],[500,600,700,800]]
matrix_example


[[0, 5, 10, 15], [20, 20, 40, 50], [500, 600, 700, 800]]

In [7]:
matrix = np.array(matrix_example)
print(matrix)

[[  0   5  10  15]
 [ 20  20  40  50]
 [500 600 700 800]]


In [8]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(0,16,3)

array([ 0,  3,  6,  9, 12, 15])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(2)

array([1., 1.])

In [14]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
np.linspace(-2,2,5)

array([-2., -1.,  0.,  1.,  2.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(6)

array([0.45712163, 0.41780239, 0.03745411, 0.90079736, 0.62880985,
       0.84723644])

In [19]:
np.random.rand(3,3,4)

array([[[0.45537377, 0.37612369, 0.67017564, 0.23951928],
        [0.93759805, 0.69741675, 0.88830545, 0.92284   ],
        [0.64148006, 0.56022944, 0.04167813, 0.50175434]],

       [[0.10345475, 0.89298333, 0.28665906, 0.70761712],
        [0.30296982, 0.66920124, 0.92689855, 0.54272437],
        [0.85824583, 0.49135412, 0.24149101, 0.3080025 ]],

       [[0.95218447, 0.84879013, 0.82261539, 0.13948787],
        [0.82060656, 0.33841473, 0.56345624, 0.75671633],
        [0.32715751, 0.62444044, 0.42834532, 0.2769475 ]]])

In [20]:
np.random.randn(5)

array([ 0.37028607,  2.04590205, -0.45880606, -1.34956067, -1.28840737])

In [21]:
np.random.randn(2,2,4)

array([[[ 0.05618421, -1.48231012,  0.67696253,  0.97207913],
        [ 0.40686061,  1.19267689, -0.91392073,  0.57799155]],

       [[-1.98954239,  0.46827101,  0.20634823, -0.27065585],
        [-1.29791897, -1.36225473, -0.18840199,  0.93371427]]])

In [24]:
np.random.randint(2,10)

7

In [25]:
np.random.randint(17,60,10)

array([34, 56, 52, 42, 24, 33, 58, 30, 25, 31])

In [26]:
Test_array1 = np.arange(9)
Test_array2 = np.random.randint(0,25,10)

In [27]:
Test_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
Test_array2

array([14, 23, 20, 24, 20,  6, 22,  9,  0,  5])

In [32]:
Test_array1.shape

(9,)

In [34]:
Test_array2.max()

24

In [35]:
Test_array2.argmax()

3

In [36]:
Test_array2.min()

0

In [37]:
Test_array2.argmin()

8

In [38]:
Test_array1.dtype

dtype('int32')

In [39]:
import numpy as np
Test_array1= np.arange(9)
Test_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
Test_array1 + Test_array1 


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [41]:
Test_array1 * Test_array1 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [42]:
Test_array1 - Test_array1 

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
Test_array1 / Test_array1 

<ipython-input-43-bb17eac676e7>:1: RuntimeWarning: invalid value encountered in true_divide
  Test_array1 / Test_array1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [44]:
1 / Test_array1

<ipython-input-44-af17ed3d8fb9>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / Test_array1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     ])

In [45]:
Test_array1 **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [46]:
np.sqrt(Test_array1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [47]:
np.exp(Test_array1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [48]:
np.max(Test_array1)

8

In [49]:
np.cosh(Test_array1)

array([1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.00676620e+01,
       2.73082328e+01, 7.42099485e+01, 2.01715636e+02, 5.48317035e+02,
       1.49047916e+03])

In [50]:
np.log(Test_array1)

<ipython-input-50-549a21c78342>:1: RuntimeWarning: divide by zero encountered in log
  np.log(Test_array1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154])

In [51]:
import numpy as np

In [52]:
arr = np.arange(0,11)
Test_array1 = np.arange(9)
Test_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
Test_array1[3]

3

In [55]:
Test_array1[2:7]

array([2, 3, 4, 5, 6])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
Test_array1_section = Test_array1[0:6]
Test_array1_section

array([0, 1, 2, 3, 4, 5])

In [61]:
Test_array1_section [:] = 999
Test_array1_section

array([999, 999, 999, 999, 999, 999])

In [62]:
Test_array1

array([999, 999, 999, 999, 999, 999,   6,   7,   8])

In [69]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
slice_off_arr = arr[0:6]
slice_off_arr

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_off_arr [:]=99
slice_off_arr

array([99, 99, 99, 99, 99, 99])

In [73]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
mat_2d=np.array(([0,5,10],[15,20,25],[30,35,40]))
mat_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [76]:
arr_2d[1]

array([20, 25, 30])

In [77]:
arr_2d[1][0]

20

In [78]:
mat_2d[1,0]

15

In [79]:
mat_2d[:2:1]

array([[ 0,  5, 10],
       [15, 20, 25]])

In [80]:
mat_2d[2,:]

array([30, 35, 40])

In [81]:
arr2d=np.zeros((10,10))

In [82]:
arr_lenght = arr2d.shape[1]

In [83]:
for i in range(arr_lenght):
    arr2d[i]=i
 
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [84]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [85]:
Test_array1 > 4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [88]:
arr=np.arange(1,11)
arr
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [89]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
x=12
mat_2d[mat_2d>x]

array([15, 20, 25, 30, 35, 40])